// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SRD_RemoveFadedContinue","status":true,"description":"This Plugin removes the faded out \"continue\" choice from\r\nthe choices at the title screen.","parameters":{}},
{"name":"MOG_CharSelect","status":true,"description":"(v1.1) Cena de seleção de personagens.","parameters":{"Initial Party Size":"4","Hide Actor IDs":"101,102,105,106","Ring Size":"200","Face X-Axis":"30","Face Y-Axis":"0","Face 2 X-Axis":"690","Face Y X-Axis":"150","Face Face 2 Space":"90","Picture X-Axis":"70","Picture Y-Axis":"0","Cursor X-Axis":"0","Cursor Y-Axis":"0","Cursor Rotation":"0.02","Name X-Axis":"20","Name Y-Axis":"525","Par X-Axis":"270","Par Y-Axis":"200","Par Font Size":"22"}}
];
